<template>
  <div class="space-y-8">
    <div class="text-center">
      <h2 class="text-3xl font-bold text-gray-900">Your Estimate</h2>
      <p class="mt-2 text-gray-600">Based on your project parameters</p>
    </div>
    
    <EstimateSummary :result="result" />
    
    <div class="card">
      <h3 class="text-lg font-semibold text-gray-900 mb-4">Timeline</h3>
      <TimelineBar :result="result" />
    </div>
    
    <div class="card">
      <h3 class="text-lg font-semibold text-gray-900 mb-4">Detailed Breakdown</h3>
      <EstimateBreakdown :breakdown="result.breakdown" />
    </div>
    
    <div class="flex justify-center gap-4">
      <button @click="copyEstimate" class="btn-secondary">
        <svg class="w-5 h-5 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 5H6a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2v-1M8 5a2 2 0 002 2h2a2 2 0 002-2M8 5a2 2 0 012-2h2a2 2 0 012 2m0 0h2a2 2 0 012 2v3m2 4H10m0 0l3-3m-3 3l3 3" />
        </svg>
        Copy Estimate
      </button>
      <button @click="$emit('restart')" class="btn-primary">
        Start Over
      </button>
    </div>
  </div>
</template>

<script setup lang="ts">
import type { CalculatorResult } from '@/types'
import EstimateSummary from '@/components/calculator/EstimateSummary.vue'
import TimelineBar from '@/components/calculator/TimelineBar.vue'
import EstimateBreakdown from '@/components/calculator/EstimateBreakdown.vue'

interface Props {
  result: CalculatorResult
}

const props = defineProps<Props>()

defineEmits<{
  restart: []
}>()

function copyEstimate() {
  if (!props.result) return
  
  const text = `Frontend Project Estimate
========================

Total Hours: ${props.result.finalHours}
Timeline (1 dev): ${props.result.timeline1Dev} weeks
Timeline (2 devs): ${props.result.timeline2Devs} weeks

Breakdown:
${props.result.breakdown.map(item => `${item.label}: ${item.hours} hrs`).join('\n')}

Generated by Frontend Time Estimator`

  navigator.clipboard.writeText(text).then(() => {
    alert('Estimate copied to clipboard!')
  }).catch(() => {
    alert('Failed to copy. Please try again.')
  })
}
</script>
