import type { WizardState } from '@/types';
export declare const useWizardStore: import("pinia").StoreDefinition<"wizard", Pick<{
    state: import("vue").Ref<{
        currentStep: number;
        p1: number;
        p2: number;
        p3a: number;
        p3b: number;
        p3c: number;
        p4a: number;
        p4b: number;
        p5: number;
        optionalFeatures: string[];
        isComplete: boolean;
    }, WizardState | {
        currentStep: number;
        p1: number;
        p2: number;
        p3a: number;
        p3b: number;
        p3c: number;
        p4a: number;
        p4b: number;
        p5: number;
        optionalFeatures: string[];
        isComplete: boolean;
    }>;
    totalSteps: number;
    canGoNext: import("vue").ComputedRef<boolean>;
    canGoPrev: import("vue").ComputedRef<boolean>;
    isLastStep: import("vue").ComputedRef<boolean>;
    nextStep: () => void;
    prevStep: () => void;
    goToStep: (step: number) => void;
    updateParam: (key: keyof WizardState, value: number | string[]) => void;
    toggleOptionalFeature: (featureId: string) => void;
    complete: () => void;
    reset: () => void;
    loadScenario: (params: {
        p1: number;
        p2: number;
        p3a: number;
        p3b: number;
        p3c: number;
        p4a: number;
        p4b: number;
        p5: number;
    }, features?: string[]) => void;
}, "state" | "totalSteps">, Pick<{
    state: import("vue").Ref<{
        currentStep: number;
        p1: number;
        p2: number;
        p3a: number;
        p3b: number;
        p3c: number;
        p4a: number;
        p4b: number;
        p5: number;
        optionalFeatures: string[];
        isComplete: boolean;
    }, WizardState | {
        currentStep: number;
        p1: number;
        p2: number;
        p3a: number;
        p3b: number;
        p3c: number;
        p4a: number;
        p4b: number;
        p5: number;
        optionalFeatures: string[];
        isComplete: boolean;
    }>;
    totalSteps: number;
    canGoNext: import("vue").ComputedRef<boolean>;
    canGoPrev: import("vue").ComputedRef<boolean>;
    isLastStep: import("vue").ComputedRef<boolean>;
    nextStep: () => void;
    prevStep: () => void;
    goToStep: (step: number) => void;
    updateParam: (key: keyof WizardState, value: number | string[]) => void;
    toggleOptionalFeature: (featureId: string) => void;
    complete: () => void;
    reset: () => void;
    loadScenario: (params: {
        p1: number;
        p2: number;
        p3a: number;
        p3b: number;
        p3c: number;
        p4a: number;
        p4b: number;
        p5: number;
    }, features?: string[]) => void;
}, "canGoNext" | "canGoPrev" | "isLastStep">, Pick<{
    state: import("vue").Ref<{
        currentStep: number;
        p1: number;
        p2: number;
        p3a: number;
        p3b: number;
        p3c: number;
        p4a: number;
        p4b: number;
        p5: number;
        optionalFeatures: string[];
        isComplete: boolean;
    }, WizardState | {
        currentStep: number;
        p1: number;
        p2: number;
        p3a: number;
        p3b: number;
        p3c: number;
        p4a: number;
        p4b: number;
        p5: number;
        optionalFeatures: string[];
        isComplete: boolean;
    }>;
    totalSteps: number;
    canGoNext: import("vue").ComputedRef<boolean>;
    canGoPrev: import("vue").ComputedRef<boolean>;
    isLastStep: import("vue").ComputedRef<boolean>;
    nextStep: () => void;
    prevStep: () => void;
    goToStep: (step: number) => void;
    updateParam: (key: keyof WizardState, value: number | string[]) => void;
    toggleOptionalFeature: (featureId: string) => void;
    complete: () => void;
    reset: () => void;
    loadScenario: (params: {
        p1: number;
        p2: number;
        p3a: number;
        p3b: number;
        p3c: number;
        p4a: number;
        p4b: number;
        p5: number;
    }, features?: string[]) => void;
}, "nextStep" | "prevStep" | "goToStep" | "updateParam" | "toggleOptionalFeature" | "complete" | "reset" | "loadScenario">>;
